# Prometheus configuration for vLLM metrics scraping
#
# Usage:
#   docker run -d -p 9090:9090 \
#     -v $(pwd)/deploy/metrics/prometheus.yml:/etc/prometheus/prometheus.yml \
#     prom/prometheus

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'vllm-demo'
    environment: 'production'

scrape_configs:
  # vLLM server metrics
  - job_name: 'vllm'
    static_configs:
      - targets: ['vllm:8000']
        labels:
          service: 'vllm-server'
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Proxy API metrics (proxied from vLLM)
  - job_name: 'vllm-proxy'
    static_configs:
      - targets: ['api:8787']
        labels:
          service: 'vllm-proxy-api'
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
